ci(test): Add Unit Test job
runs tests, creates reports

ref: #163  #162 #36

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -75,6 +75,124 @@ jobs:
 
 
 
+  test-unit:
+    name: Unit Tests
+    runs-on: ubuntu-latest
+    env:
+      # TZ has no DST and is close to west side of intl date line.
+      TZ: Australia/Darwin
+    steps:
+
+
+      - uses: actions/checkout@v4
+
+
+      - name: Setup Node
+        uses: actions/setup-node@v3
+        with:
+          node-version: 20
+
+
+      - name: Setup
+        shell: bash
+        run:
+          npm install
+
+
+      - name: Trace ICU / Locale
+        run: |
+          locale;
+
+          node -p "process.versions.icu"
+          node -e "console.log(Intl.DateTimeFormat().resolvedOptions())"
+
+          node -e "console.log(new Date().toLocaleString('default', { month: 'long' }))"
+
+          node -e "console.log(Intl.DateTimeFormat.supportedLocalesOf(['en-AU', 'en-GB', 'en-US']))";
+
+          node -e "console.log(Intl.DateTimeFormat().resolvedOptions().timeZone)";
+
+          date;
+
+          date +"%Z %z";
+
+          node -e "console.log(new Intl.DateTimeFormat('default', { month: 'long' }).format(new Date('2025-06-01')))";
+          node -e "console.log(new Intl.DateTimeFormat('en-AU', { month: 'long' }).format(new Date('2025-06-01')))";
+          node -e "console.log(new Intl.DateTimeFormat('en-US', { month: 'long' }).format(new Date('2025-06-01')))";
+          node -e "console.log(new Intl.DateTimeFormat('en-GB', { month: 'long' }).format(new Date('2025-06-01')))";
+
+          node -e "console.log(new Intl.DateTimeFormat('default', { month: 'short' }).format(new Date('2025-06-01')))";
+          node -e "console.log(new Intl.DateTimeFormat('en-AU', { month: 'short' }).format(new Date('2025-06-01')))";
+          node -e "console.log(new Intl.DateTimeFormat('en-US', { month: 'short' }).format(new Date('2025-06-01')))";
+          node -e "console.log(new Intl.DateTimeFormat('en-GB', { month: 'short' }).format(new Date('2025-06-01')))";
+
+
+      - name: Run Tests
+        shell: bash
+        run:
+          npm test -- --testPathPatterns="__test__/unit"
+
+
+      - name: Obtain Test Data
+        id: test-data
+        if: success() || failure()
+        shell: bash
+        run: |
+          echo "COVERAGE_LINES=$(jq -r '.total.lines.pct' artifacts/coverage/coverage-summary.json)" >> $GITHUB_OUTPUT;
+          echo "COVERAGE_BRANCH=$(jq -r '.total.branches.pct' artifacts/coverage/coverage-summary.json)" >> $GITHUB_OUTPUT;
+
+          echo "${COVERAGE_LINES} - ${COVERAGE_BRANCH}";
+
+
+          echo "TESTS_NUM_PASSED=$(jq -r '.numPassedTests' artifacts/test_results.json)" >> $GITHUB_OUTPUT;
+          echo "TESTS_NUM_SKIPPED=$(jq -r '.numPendingTests' artifacts/test_results.json)" >> $GITHUB_OUTPUT;
+          echo "TESTS_NUM_FAILED=$(jq -r '.numFailedTests' artifacts/test_results.json)" >> $GITHUB_OUTPUT;
+
+
+
+
+      - name: Create Coverage Shields.io Endpoint
+        if: success() || failure()
+        shell: bash
+        run: |
+          echo '
+            {
+              "schemaVersion": 1,
+              "label": "Unit Test Coverage",
+              "labelColor": "#323330",
+              "message": "${{ steps.test-data.outputs.COVERAGE_LINES }}% Line | ${{ steps.test-data.outputs.COVERAGE_BRANCH }}% Branch",
+              "logoSvg": "<svg enable-background=\"new 0 0 398.3 439.9\" viewBox=\"0 0 398.3 439.9\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"m334.9 218.1c-.5.3-18.3-2.7-40.7-4.2-18.2-1.2-39.5-1.2-56.7 0-14 .9-32.4-6.1-34.6 2.3-8.2 31.4-26 58.7-48.5 79.9-17 16-36.4 28.1-57.4 35.6-25-12.8-36.8-41.4-26.2-66.4 8.4-19.9 18.3-41.7.1-46.7-13.2-3.6-20.5 9-25.5 22.5-9.7 25.9-28.2 52.7-33.5 84.5-5.6 33.5 0 69.1 29 89.3 67.6 46.8 140.9-29 218.2-48.1 28-6.9 58.8-5.8 83.5-20.1 18.5-10.7 30.8-28.5 34.2-48.5 5.6-32.2-11.1-64.1-41.9-80.1z\" fill=\"#99425b\" stroke=\"#fff\" stroke-width=\"20\"/><path d=\"m202.9 216.2c-8.2 31.4-26 58.7-48.5 79.9-17 16-36.4 28.1-57.4 35.6-25-12.8-36.8-41.4-26.2-66.4 8.4-19.9 18.3-41.7.1-46.7-13.2-3.6-20.5 9-25.5 22.5-9.7 25.9-28.2 52.7-33.5 84.5-5.6 33.5 0 69.1 29 89.3 67.6 46.8 140.9-29 218.2-48.1 28-6.9 58.8-5.8 83.5-20.1 18.5-10.7 30.8-28.5 34.2-48.5 5.6-32.1-11.1-64.1-41.9-80\" fill=\"none\" stroke=\"#fff\" stroke-width=\"20\"/><path d=\"m264.9 91.2 54.3 110.8 65.1-192h-239l65 191.6z\" fill=\"#99425b\"/><path d=\"m264.9 91.2 54.3 110.8 65.1-192h-239l65 191.6z\" fill=\"none\" stroke=\"#fff\" stroke-width=\"20\"/><circle cx=\"199\" cy=\"216.6\" fill=\"#99425b\" r=\"40.9\"/><g stroke=\"#fff\" stroke-width=\"20\"><circle cx=\"199\" cy=\"216.6\" fill=\"none\" r=\"40.9\"/><circle cx=\"332.4\" cy=\"216.6\" fill=\"#99425b\" r=\"40.9\"/><circle cx=\"332.4\" cy=\"216.6\" fill=\"none\" r=\"40.9\"/></g><circle cx=\"65.1\" cy=\"216.9\" fill=\"#99425b\" r=\"40.9\"/><circle cx=\"65.1\" cy=\"216.9\" fill=\"none\" r=\"40.9\" stroke=\"#fff\" stroke-width=\"20\"/></svg>",
+              "color": "#F0DB4F",
+              "style": "plastic"
+            }' > artifacts/badge_endpoint_test_coverage.json;
+
+
+
+      - name: Create Test Result Shields.io Endpoint
+        if: success() || failure()
+        shell: bash
+        run: |
+          echo '
+          {
+            "schemaVersion": 1,
+            "label": "Unit Test",
+            "labelColor": "#323330",
+            "message": "${{ steps.test-data.outputs.TESTS_NUM_PASSED }} passed | ${{ steps.test-data.outputs.TESTS_NUM_SKIPPED }} skipped | ${{ steps.test-data.outputs.TESTS_NUM_FAILED }} failed",
+            "logoSvg": "<svg enable-background=\"new 0 0 398.3 439.9\" viewBox=\"0 0 398.3 439.9\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"m334.9 218.1c-.5.3-18.3-2.7-40.7-4.2-18.2-1.2-39.5-1.2-56.7 0-14 .9-32.4-6.1-34.6 2.3-8.2 31.4-26 58.7-48.5 79.9-17 16-36.4 28.1-57.4 35.6-25-12.8-36.8-41.4-26.2-66.4 8.4-19.9 18.3-41.7.1-46.7-13.2-3.6-20.5 9-25.5 22.5-9.7 25.9-28.2 52.7-33.5 84.5-5.6 33.5 0 69.1 29 89.3 67.6 46.8 140.9-29 218.2-48.1 28-6.9 58.8-5.8 83.5-20.1 18.5-10.7 30.8-28.5 34.2-48.5 5.6-32.2-11.1-64.1-41.9-80.1z\" fill=\"#99425b\" stroke=\"#fff\" stroke-width=\"20\"/><path d=\"m202.9 216.2c-8.2 31.4-26 58.7-48.5 79.9-17 16-36.4 28.1-57.4 35.6-25-12.8-36.8-41.4-26.2-66.4 8.4-19.9 18.3-41.7.1-46.7-13.2-3.6-20.5 9-25.5 22.5-9.7 25.9-28.2 52.7-33.5 84.5-5.6 33.5 0 69.1 29 89.3 67.6 46.8 140.9-29 218.2-48.1 28-6.9 58.8-5.8 83.5-20.1 18.5-10.7 30.8-28.5 34.2-48.5 5.6-32.1-11.1-64.1-41.9-80\" fill=\"none\" stroke=\"#fff\" stroke-width=\"20\"/><path d=\"m264.9 91.2 54.3 110.8 65.1-192h-239l65 191.6z\" fill=\"#99425b\"/><path d=\"m264.9 91.2 54.3 110.8 65.1-192h-239l65 191.6z\" fill=\"none\" stroke=\"#fff\" stroke-width=\"20\"/><circle cx=\"199\" cy=\"216.6\" fill=\"#99425b\" r=\"40.9\"/><g stroke=\"#fff\" stroke-width=\"20\"><circle cx=\"199\" cy=\"216.6\" fill=\"none\" r=\"40.9\"/><circle cx=\"332.4\" cy=\"216.6\" fill=\"#99425b\" r=\"40.9\"/><circle cx=\"332.4\" cy=\"216.6\" fill=\"none\" r=\"40.9\"/></g><circle cx=\"65.1\" cy=\"216.9\" fill=\"#99425b\" r=\"40.9\"/><circle cx=\"65.1\" cy=\"216.9\" fill=\"none\" r=\"40.9\" stroke=\"#fff\" stroke-width=\"20\"/></svg>",
+            "color": "#F0DB4F",
+            "style": "plastic"
+          }' > artifacts/badge_endpoint_test_unit.json;
+
+
+      - name: Upload Reports
+        if: success() || failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-unit
+          path: artifacts/
+
+
+
   gitlab-mirror:
     if: ${{ github.repository == 'nofusscomputing/centurion_erp_ui' }}
     runs-on: ubuntu-latest
